############################################################
# Copied this script from Engineering Man on Youtube (with minor tweeks)
# to run: 
# python scam_spam.py
# Did it to attack a scammer
############################################################

import requests
import os
import random
import string
import json




names = [
"Rheanna Mooney",
"Esha Norman",
"Rikesh Hayes",
"Ivy Buchanan",
"Laiba Lyon",
"Prisha Ramirez",
"Daanyaal Michael",
"Michalina Morse",
"Macauly Ellwood",
"Dilan Pennington",
"Emmeline Calvert",
"Kellie Stokes",
"Betty Terry",
"Emmie Fox",
"Jaheim Wheatley",
"Sierra Webster",
"Ameera Haley",
"Aleyna Newman",
"Carly Randall",
"Maude Mclean",
"Logan Caldwell",
"Haaris Case",
"Sapphire Blundell",
"Ammara Leach",
"Paulina Amin",
"Kaidan Fisher",
"Finlay West",
"Musa Partridge",
"Musab Emerson",
"Chad Britton",
"Jaxon Lam",
"Krishan Head",
"Ritchie Greenaway",
"Kasey Bauer",
"Karla Bevan",
"Ahmet Kelley",
"Melissa Ellis",
"Lainey Hoover",
"Autumn Lawson",
"Kirsten Blake",
"Alessandra House",
"Emma-Louise Richards",
"Hywel Shea",
"Fearne Eastwood",
"Eduard Ellison",
"Kishan Wyatt",
"August Summers",
"Faizan Kirby",
"Rajan Connolly",
"Deniz Mendez",
"Trixie Acosta",
"Gabija Graves",
"Aleeza Dean",
"Caleb Keeling",
"Brittney Cannon",
"Jaydn Peralta",
"Anthony Dorsey",
"Yazmin Webber",
"Mariyam Kaye",
"Ellenor Valdez",
"Jagdeep Weber",
"Marjorie Townsend",
"Penny Schwartz",
"Mara Dunn",
"Hope Aguirre",
"Wilf Frame",
"Liliana Whitehouse",
"Bryce Coulson",
"Chloe-Louise Lamb",
"Humayra Harper",
"T-Jay Ware",
"Ahyan Pate",
"Nabeela Lynn",
"Tre Joyce",
"Herman Cresswell",
"Annabel Price",
"Mischa Mcconnell",
"Ifan O'Quinn",
"Tyriq Haines",
"Misha Durham",
"Thierry Robson",
"Esme-Rose Rosa",
"Jadon Irving",
"Angel Haigh",
"Hayleigh Horn",
"Ashley Conway",
"Lily-Ann Mcgee",
"Hareem Byers",
"Keiren Huffman",
"Isabella Deacon",
"Luis Coles",
"Humza Andrews",
"Tj Dickson",
"Cole Huff",
"Andreas Tierney",
"Bea Moss",
"Daisie Hogg",
"Alby Smart",
"Keiran Higgins",
"Blessing Booker",
"Ottilie Finley",
"Earl Thatcher",
"Callam Burn",
"Trey Moyer",
"Harri Langley",
"Keely Mohammed",
"Lily-Ann Nairn",
"Doris Swift",
"Edmund Compton",
"Saqlain Mata",
"Suzanna Thomas",
"Halima Ramsay",
"Khalil Rowley",
"Eleni Cuevas",
"Hanifa Meza",
"Sabah Lister",
"Ivy-Rose Vincent",
"Gene Phillips",
"Reis Forster",
"Tyron Chung",
"Zander Timms",
"Amaan Cordova",
"Anne Beech",
"Fred Fry",
"Lily-Anne Mckenna",
"Ainsley Levy",
"Priyanka Daly",
"Gabriella Woolley",
"Isa Huff",
"Jaskaran Arias",
"Lilly-May Emerson",
"Susan Steadman",
"Tyreese Campos",
"Tj Mcguire",
"Roger Arellano",
"Efan Mann",
"Mayur Stephens",
"Cristina Ratcliffe",
"Jaime Cannon",
"Anya Bright",
"Amalie Robson",
"Aled William",
"Matthew Benson",
"Leon Tapia",
"Isla Haley",
"Vienna Lee",
"Raiden Davidson",
"Rhianne Mcleod",
"Sadie Cochran",
"Syeda Buchanan",
"Sierra Spencer",
"Frederic Wyatt",
"Rahma Bowers",
"Essa Marin",
"Dilan Maldonado",
"Gladys Sheehan",
"Veronica Robin",
"Rianne Rossi",
"Brenda Burnett",
"Emme Ratliff",
"Demi Ray",
"Isha Lutz",
"Kerrie Horner",
"Emaan Gray",
"Susie Pearce",
"Sylvia Mcintosh",
"Diogo Jennings",
"Alicja Blevins",
"Khaleesi Combs",
"Ayaz Braun",
"Garfield Ingram",
"Shaun Daniel",
"Elana Dickinson",
"Aditya Rosa",
"Kylie Fitzpatrick",
"Marian Beck",
"Boyd Britton",
"Jordan-Lee Ellison",
"Habibah Marsh",
"Aniqa Feeney",
"Elicia Webb",
"Kerri Cohen",
"Beverley Broadhurst",
"Polly Austin",
"Joanna Ayers",
"Vishal Wagner",
"Elyse Lynn",
"Elif Amos",
"Oliwier Lyon",
"Marta Sanford",
"Ceara Ford",
"Amiee Enriquez",
"Rio Garrett",
"Kaitlan Roche",
"Jethro Greig",
"Anabel Winters",
"Kaylum Gill",
"Montague Rutledge",
"Amaya Valdez",
"Kaia Hackett",
"Parris Beach",
"Timothy Ewing",
"Nichola Jimenez",
"Beck Arroyo",
"India Dowling",
"Merlin Ryder",
"Gurpreet Dunlap",
"Albie Mccartney",
"Rohaan Oconnell",
"Ruby-Leigh Wright",
"Jamil Heath",
"Hussain Gough",
"Frederick Weaver",
"Romana Stubbs",
"Fern Beil",
"Brennan Villa",
"Jia Merrill",
"Zuzanna Mendoza",
"Greta Needham",
"Anaiya Vargas",
"Eryk Vazquez",
"Cecil Wolfe",
"Jill Mcphee",
"Cassie Wu",
"Jean Camacho",
"Laurence Ali",
"Buster Draper",
"Marianna Pemberton",
"Patricia Joyner",
"Zeeshan Harper",
"Willow Waller",
"Lucia Singleton",
"Drew Hood",
"Catriona Devine",
"Kwabena Hoffman",
"Dixie Figueroa",
"Monique Skinner",
"Esme Kouma",
"Melinda Hickman",
"Musab Coffey",
"Donovan Talley",
"Gerrard Parkes",
"Selena Tomlinson",
"Ciara Callahan",
"Kalum Bond",
"Star Booker",
"Darsh Mcfadden",
"Douglas Stone",
"Ruqayyah Mccall",
"Trystan Tate",
"Franco Travis",
"Edith Forrest",
"Makenzie Soto",
"Ruby-Rose Hatfield",
"Graham Simmons",
"Sannah Horn",
"Katharine Dupont",
"Glyn Ridley",
"Shirley Wheatley",
"Kymani Lambert",
"Igor Plant",
"Kaiser Jacobs",
"Nicole Kumar",
"Khadija Tillman",
"Raja Bolton",
"Jake Newman",
"Homer Mckay",
"Kimberly Moran",
"Mcauley Esquivel",
"Raj Hook",
"Fahim Sykes",
"Henri East",
"Jimi Gamble",
"Lola Bowen",
"Willa Enriquez",
"Tye Contreras",
"Rayyan Greer",
"Eugene Wilkins",
"Ruari Garrett",
"Marcelina Rudd",
"Jeremy Snyder",
"Eshan Gonzalez",
"Khia Farrow",
"Charlotte Michael",
"Luna French",
"Colby Spencer",
"Alya Shields",
"Cassandra Whitmore",
"Louis Dodson",
"Odin Cope",
"Tallulah Beaumont",
"Kai Person",
"Linzi Mcarthur",
"Atlanta Mahoney",
"Stuart Bautista",
"Hugh Rich",
"Kelsea Noble",
"Zainab Storey",
"Kiri Navarro",
"Molly Stuart",
"Evalyn Partridge",
"Roscoe Gardiner",
"Simrah Bennett",
"Jayden-Lee Wills",
"Billy-Joe Calvert",
"Hope Pena",
"Shay David",
"Rhiana Snyder",
"Emelie Roche",
"Terry Mcmillan",
"Alexia Craig",
"Selena Norris",
"Ewen Ashley",
"Cindy George",
"Akshay Aldred",
"Gracie-Mai Li",
"Madina Bray",
"Leila Noble",
"Joanna Dupont",
"Brad Mcneil",
"Aleksandra Buchanan",
"Hunter Adkins",
"Yaqub Warren",
"Jozef Martinez",
"Kellan Cisneros",
"Lucinda English",
"Martyn Bender",
"Zoe Steadman",
"Avni Mccormick",
"Natasha Fleming",
"Cheyanne Koch",
"Becky Tucker",
"Diana Healy",
"Gwen Vaughn",
"Sameera Yang",
"Rhyley Myers",
"Miruna Mccallum",
"Tabatha Ali",
"Nicky Whittle",
"Darin Dale",
"Nellie Lugo",
"Ruby-Leigh O'Connor",
"Aadam Swanson",
"Piotr Lloyd",
"Hugh Cabrera",
"Anika Branch",
"Reid Schroeder",
"Rares Harris",
"Loren Paine",
"Lianne Cook",
"Elysha Kelley",
"Sanjay Buxton",
"Ellisha Harrison",
"Hadiqa Crouch",
"Effie Figueroa",
"Menachem Dawson",
"Emre Timms",
"Samanta Nicholson",
"Miya Beck",
"Daisie Serrano",
"Mohamed Cote",
"Tanner Guy",
"Jonah Sandoval",
"Sheridan Wallace",
"Darnell Mayer",
"Hussain Battle",
"Winifred Conroy",
"Judy Reynolds",
"Leah Hackett",
"Rogan Ellison",
"Campbell Medrano",
"Gabriela Stamp",
"Juliette Mcgrath",
"Bryce Donaldson",
"Quentin Ortega",
"Adyan Daugherty",
"Sahib William",
"Huxley Black",
"Nile Churchill",
"Hollie Steele",
"Mohammad Hogan",
"Nettie Price",
"Reeva Kirby",
"Makenzie Phillips",
"Laylah Harper",
"Zayna Khan",
"Vivian Barron",
"Nour Mcconnell",
"Grace O'Neill",
"Ivor Drew",
"Jesse Rees",
"Umaiza Sharp",
"Jedd Whitney",
"Romario Stokes",
"Brenna Davies",
"Malaika Parra",
"Neo Mitchell",
"Aadil Mendoza",
"Cieran Clay",
"Hibah Quintero",

]




char = string.digits + '!@#$@^$#%$'
chars = [i for i in char]
random.seed = (os.urandom(1024))
url = '' ## Insert link to their website here
print(chars)
count = 0

name_new = [name.split() for name in names]
name_nn = [z for x in name_new for z in x]
# print(name_nn)
# for name in names:
for i in name_nn:
	random.shuffle(chars)
	temp = ''.join(chars)
	username = i.lower() + str(random.randint(1000,1000000))
	random.shuffle(chars)
	password = ''.join(chars)

	# print('u: ' + username)
	# print('p: ' + password)
	requests.post(url, allow_redirects=False, data = {'a': username, 'b': password})
	#requests.post(url, allow_redirects=False, data = {'userId': username, 'password': password})
	#requests.post(url, allow_redirects=False, data = {'kdhkkaf': username, 'uukschk': password})
	print('Sending user ' + username + ' password ' + password)





